### ISSUE TITLE
solr 5.5.2 Data source not found.

### ISSUE THREAD

**Issue by 99ttz** [shopping24/solr-jdbc#2]
Hi,

I'm trying to use solr with jdbc backend for synonyms. I have compiled the plugin by hand and modified the pom.xml as to build agains solr 5.5.2.

Also, i have made the following configurations:

solrconfig.xml:
< lib dir="${solr.install.dir:../../../..}/contrib/dataimporthandler/lib" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-dataimporthandler-.*\.jar" />

  < lib dir="${solr.install.dir:../../../..}/contrib/jdbc" regex=".*\.jar" />

< dataConfig >
    < dataSource type="com.s24.search.solr.analysis.jdbc.DataImportJdbcDataSource"
                name="jdbc/ds_syno"
                dataSource="jdbc/synonyms" />
    < dataSource type="JdbcDataSource"
                name="jdbc/synonyms"
                driver="org.postgresql.Driver"
                url="jdbc:postgresql://hdp01.local:5432/synonyms"
                user="username"
                password="password" />
</ dataConfig >

managed-schema:

  < fieldType name="text_searchable" class="solr.TextField">
     < analyzer type="query">
        < tokenizer class="solr.PatternTokenizerFactory" pattern="[\s]+" />
        < filter class="com.s24.search.solr.analysis.jdbc.JdbcSynonymFilterFactory"
          sql="SELECT concat(lhs, '=>', rhs) as line FROM synonyms"
          dataSource="jdbc/ds_syno" ignoreCase="true" expand="true" />
        < filter class="solr.LowerCaseFilterFactory"/>
        < filter class="solr.TrimFilterFactory" />
        < filter class="solr.PorterStemFilterFactory"/>
        < filter class="solr.RemoveDuplicatesTokenFilterFactory"/>
     < /analyzer>
  < /fieldType>

But when i try to create a new collection i get the following error:

"Data source jdbc/ds_syno not found."

Any ideas?

Best
T

**Comment by tboeghk** [comment]
it seems that you configured a Solr data config and not a Tomcat JNDI data source. The Solr JDBC plugin utilizes a Tomcat JNDI data source: http://tomcat.apache.org/tomcat-8.5-doc/jndi-resources-howto.html#JDBC_Data_Sources

**Comment by 99ttz** [comment]
Correct, but my solr uses jetty and not Tomcat. I have also tried the following in jetty:

Web.xml:

< resource-ref>
        < description>my datasource</description>
        < res-ref-name>ds_syno</res-ref-name>
        < res-type>javax.sql.DataSource</res-type>
        < res-auth>Container</res-auth>
    < /resource-ref>

solr-jetty-context.xml:

< New id="dsTest" class="org.eclipse.jetty.plus.jndi.Resource">
     < Arg></Arg>
     < Arg>ds_syno</Arg>
     <  Arg>
        < New class="org.postgresql.Driver">
           < Set name="User">username</Set>
           < Set name="Password">password</Set>
           < Set name="DatabaseName">synonims</Set>
           < Set name="ServerName">hdp01.local</Set>
           < Set name="PortNumber">5432</Set>
        < /New>
     < /Arg>
  < /New>

But still does not work :(

Any pointers?

Best
T

**Comment by tboeghk** [comment]
Configure the JNDI datasource in Jetty. Check via JMX and log files if it is present and running. Remove the `dataConfig` from Solr. It is not recognized by the plugin. The only configuration needed on the Solr side is

```< filter class="com.s24.search.solr.analysis.jdbc.JdbcSynonymFilterFactory"
sql="SELECT concat(lhs, '=>', rhs) as line FROM synonyms"
dataSource="jdbc/ds_syno" ignoreCase="true" expand="true" />```

Double check that the JNDI namings *all* match `jdbc/ds_syno`. In the example above they don't: https://wiki.eclipse.org/Jetty/Howto/Configure_JNDI_Datasource#Introduction

**Comment by 99ttz** [comment]
I have modified web.xml to:

< resource-ref >
        < description>my datasource< /description>
        < res-ref-name>ds_syno< /res-ref-name>
        < res-type>javax.sql.DataSource< /res-type>
        < res-auth>Container< /res-auth>
    < /resource-ref >
< New id="dsTest" class="org.eclipse.jetty.plus.jndi.Resource">
     < Arg>< /Arg>
     < Arg>jdbc/ds_syno< /Arg>
     < Arg>
        < New class="org.postgresql.ds.PGSimpleDataSource">
           < Set name="User">username< /Set>
           < Set name="Password">password< /Set>
           < Set name="DatabaseName">synonims< /Set>
           < Set name="ServerName">hdp01.local< /Set>
           < Set name="PortNumber">5432< /Set>
        < /New>
     < /Arg>
  < /New >

**Comment by 99ttz** [comment]
The main issue was that jndi support was not enabled in solr. The below needs to be added to the context. Leaving this for others that might encounter similar issues; many thanks tboeghk for support.

`  
< Array id="plusConfig" type="java.lang.String" >
    < Item>org.eclipse.jetty.webapp.WebInfConfiguration< /Item>
    < Item>org.eclipse.jetty.webapp.WebXmlConfiguration< /Item>
    < Item>org.eclipse.jetty.webapp.MetaInfConfiguration< /Item>
    < Item>org.eclipse.jetty.webapp.FragmentConfiguration< /Item>
    < Item>org.eclipse.jetty.plus.webapp.EnvConfiguration< /Item> 
    < Item>org.eclipse.jetty.plus.webapp.PlusConfiguration< /Item>  
    < Item>org.eclipse.jetty.webapp.JettyWebXmlConfiguration< /Item>
  < /Array>

    <Set name="configurationClasses"><Ref refid="plusConfig"/></Set>
`
